### ISSUE TITLE
type_case: :camelize only sets root queries

### ISSUE THREAD

**Issue by ostrgard** [geneeblack/graphql_model_mapper#30]
Hi!

I would assume that `type_case: :camelize` would make all fields and arguments camel cased, but it seems that this configuration only have effect on root query naming. A model called `CreditCard` would generate a root query called `creditCard` (as expected), but with arguments like `item_id`, as well as fields like `exp_month`, rather than `itemId` and `expMonth`.

Am I missing something in the configuration or is this working as intended? 

I realise that the last commit to this repo were more than a year ago. Crossing my fingers that there's still some interest in this from the authors 🤞😄

Thank you in advance!

**Comment by geneeblack** [comment]
You are correct. The camelize argument only applies against the root query or mutation. This project was essentially a learning project for me to discover the feasibility of use for graphql in rails.

**Comment by ostrgard** [comment]
Thanks for getting back to me, @geneeblack!
